### ISSUE TITLE
Cann't import rxdb on angular9

### ISSUE THREAD

**Issue by molysama** [pubkey/rxdb#2324]
## Case

Bug

## Issue

I can't import anything on angular9. There are a lot of type errors at compile time.

## Info
  - @angular/cli: 9.1.1
  - rxdb: 9.3.0
  - node: 10.15.3

## Code

```js
import { createRxDatabase } from 'rxdb'
```

```
ERROR in node_modules/event-reduce-js/dist/es/index.d.ts:1:13 - error TS1005: '=' expected.

1 import type { ChangeEvent, ActionName, ResultKeyDocumentMap, QueryParams, StateSetToActionMap, StateSet, ActionFunction, StateResolveFunctionInput } from './types';
              ~
node_modules/event-reduce-js/dist/es/index.d.ts:1:155 - error TS1005: ';' expected.

1 import type { ChangeEvent, ActionName, ResultKeyDocumentMap, QueryParams, StateSetToActionMap, StateSet, ActionFunction, StateResolveFunctionInput } from './types';
                                                                                                                                                            ~~~~~~~~~
node_modules/event-reduce-js/dist/es/states/index.d.ts:2:13 - error TS1005: '=' expected.

2 import type { StateName, StateResolveFunction, StateSet, StateResolveFunctionInput } from '../types';
              ~
node_modules/event-reduce-js/dist/es/states/index.d.ts:2:91 - error TS1005: ';' expected.
```

**Comment by pubkey** [comment]
You have to upgrade your typescript version.

**Comment by molysama** [comment]
good job. It works after upgrade angular to v10.
