### ISSUE TITLE
Running rxdb as dependency fails due to missin pouchdb-adapter-memory

### ISSUE THREAD

**Issue by rybaczewa** [pubkey/rxdb#365]
## Case
Bug

## Issue
After upgrading to 7.0.0 applciation fails with `Error: Cannot find module 'pouchdb-adapter-memory'`
I assume that's because of new in-memory option. Adapter should be either moved from `devDependencies` to `dependencies` or in-memory should should be pluggable.

**Comment by pubkey** [comment]
You are right. Fix will come soon.
You can of course temporaly workarround by installing `pouchdb-adapter-memory` by hand.

**Comment by pubkey** [comment]
I added an minimal example-project which is run at travis, so we know this type of bug wont happen again.

**Comment by pubkey** [comment]
TODO fix in travis. Local works
